---
- name: Add apt-key (keyserver)
  apt_key: 
    id: "{{ mesos_apt_key_id }}"
    keyserver: "{{ mesos_apt_key_server }}"
    state: present
  when:
    - mesos_apt_key_id and mesos_apt_key_server
    - mesos_apt_key_url is not defined

- name: Add apt-key (url)
  apt_key: 
    id: "{{ mesos_apt_key_id }}"
    url: "{{ mesos_apt_key_url }}"
    state: present
  when:
    - mesos_apt_key_id and mesos_apt_key_url
    - mesos_apt_key_url is defined

- name: Add mesosphere repo
  apt_repository: repo='deb {{ mesosphere_apt_url }} {{ ansible_distribution_release | lower }} main' state=present update_cache=yes

- name: Pin Mesos version
  template:
    src: mesos.pref.j2
    dest: /etc/apt/preferences.d/mesos.pref
  when: mesos_apt_pin_priority | default(false) | bool

- name: Install Debian OS packages
  apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - "{{ mesos_apt_package }}"
